version: 2
jobs:
  build:
    build-frontend: 
    docker:
    - image: circleci/node:13.8.0
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package-lock.json" }}
        - v1-dependencies-
    - run:
        name: Install dependencies
        command: npm install
    - save_cache:
        key: v1-dependencies-{{ checksum "package-lock.json" }}
        paths:
        - node_modules
    - run:
        name: Build
        command: |
          if [ $CIRCLE_BRANCH = 'circleci-project-setup' ]; then
            npm run build
          fi
    - persist_to_workspace:
        root: .
        paths:
        - .

workflows:
  build_and_deploy:
    jobs:
    - build:
        filters:
          branches:
            only:
            - circleci-project-setup
    
  